/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#424842",
        "on-primary-fixed": "#07200f",
        "background": "#fbf9f5",
        "tertiary": "#44617c",
        "on-secondary-fixed": "#241a0e",
        "secondary-container": "#f4dfcb",
        "surface-container-high": "#eae8e4",
        "on-secondary": "#ffffff",
        "surface-dim": "#dbdad6",
        "outline": "#737972",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#524436",
        "on-error": "#ffffff",
        "tertiary-fixed": "#cde5ff",
        "primary-fixed-dim": "#b0ceb2",
        "surface-bright": "#fbf9f5",
        "inverse-primary": "#b0ceb2",
        "surface-container": "#efeeea",
        "on-primary-fixed-variant": "#334d38",
        "outline-variant": "#c2c8c0",
        "on-surface": "#1b1c1a",
        "on-tertiary-container": "#1c3a53",
        "secondary-fixed": "#f4dfcb",
        "surface-tint": "#4a654e",
        "primary": "#4a654e",
        "surface-container-low": "#f5f3ef",
        "on-error-container": "#93000a",
        "inverse-surface": "#30312e",
        "surface-container-highest": "#e4e2de",
        "on-background": "#1b1c1a",
        "tertiary-container": "#87a4c2",
        "surface-variant": "#e4e2de",
        "secondary-fixed-dim": "#d7c3b0",
        "on-tertiary-fixed-variant": "#2c4963",
        "tertiary-fixed-dim": "#accae9",
        "on-primary-container": "#233d29",
        "primary-fixed": "#cceace",
        "surface": "#fbf9f5",
        "on-secondary-container": "#716252",
        "on-tertiary-fixed": "#001d32",
        "secondary": "#6b5c4c",
        "primary-container": "#8ba88e",
        "inverse-on-surface": "#f2f0ed",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}